-- A plugin for creating autocommits while you are working on a project.
-- This plugin works with fugitive.

---@enum Actions
local ACTIONS = {
    SAVE = 0,
    WAIT = 1,
}

---Main return table for autocommit.nvim
---@type table
local M = {
    ---@type table
    commit = {
        ---When to commit.
        ---@type Actions
        when = ACTIONS.SAVE,
        ---@type fun()
        ---@return string
        header = function ()
            return os.date('[Autocommit] - %c')
        end,
        body = function ()
            return 'This was an automatic commit generated by autocommit.nvim.'
        end,
    },
}

M.create_commit = function (...)
    vim.cmd([[
    let dir = FugitiveGitDir()
    let _ = FugitiveExecute(["add", "."], dir)
    let _ = FugitiveExecute(["commit", "-m", "]]..M.commit.header()..[[", "-m", "]]..M.commit.body()..[["], dir )
    ]])
end

---Attach the automcommands to Neovim when the hook method is called.
M.hook = function()
    if M.commit.when == ACTIONS.SAVE then
        vim.api.nvim_create_autocmd(
            {'BufWritePost'},
            {
                buffer = 0,
                callback = M.create_commit,
            }
        )
    else -- M.commit.when == ACTIONS.WAIT
        vim.api.nvim_create_autocmd(
            {'CursorHold'},
            {
                buffer = 0,
                callback = M.create_commit,
            }
        )
    end
end

M.setup = function (opts)
    -- recursively copy options from opts into M.opts
    M.opts = vim.tbl_deep_extend(
        'force',
        M.opts,
        opts
    )
end

M.hook()

return M
